---
- name: Setup Remote Workstation
  gather_facts: No
  hosts: all
  tasks:
    - name: update the system
      package:
        name:  "*"
        state: latest
    - name: Install base packages
      package:
        name: ['unzip', 'vim', 'zsh', 'nginx', 'python3', 'python3-devel', 'wget', 'epel-release']
        state: present
      become: yes
    - name: Install development tools
      package:
        name: "@development"
        state: present
      become: yes
    - name: terraform install
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: True
    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
      ignore_errors: "{{ ansible_check_mode }}"
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      ignore_errors: "{{ ansible_check_mode }}"
    - name: upload custom Nginx conf
      template:
        src: ../conf/nginx.conf.j2
        dest: "/etc/nginx/nginx.conf"
    - name: Start Nginx service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      ignore_errors: "{{ ansible_check_mode }}"

- name: Create and configure users
  import_playbook: create_users.yml      

- name: Custom setup
  import_playbook: customize_workspace.yml 
