---
- name: Setup Remote Workstation
  gather_facts: No
  hosts: all
  user: root
  tasks:
    - name: Update APT package cache
      apt: update_cache=yes
    - name: Upgrade APT to the latest packages
      apt: upgrade=dist
    - name: update the system
      package:
        name:  "*"
        state: latest
        update_cache: yes
    - name: Install base packages
      package:
        name: ['unzip', 
               'vim', 
               'zsh',
               'nginx',
               'wget',
               'python3-pip',
               'build-essential',
               'libssl-dev',
               'libffi-dev',
               'python3-dev',
               'python3-venv',
               'docker.io'
              ]
        state: present
      become: yes
    - name: terraform install
      unarchive:
        src: https://releases.hashicorp.com/terraform/0.14.2/terraform_0.14.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: True
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      ignore_errors: "{{ ansible_check_mode }}"
    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
      ignore_errors: "{{ ansible_check_mode }}"
    - name: Set python3 as default python
      shell: 'update-alternatives --install /usr/bin/python python /usr/bin/python3 1'


- name: Create and configure users
  import_playbook: create_users.yml      

- name: Custom setup
  import_playbook: customize_workspace.yml 
